# Generated by Django 3.0.5 on 2020-05-05 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200430_1850'),
        ('list_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listitemmodel',
            unique_together={('listmodel_id', 'name', 'expiration_date')},
        ),
    ]
